name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 15 * * *'

jobs:
  test_mac:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [mac-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Download Roswell
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          brew install roswell
      - name: Install Rove
        run: ros install rove
      - name: Run tests
        run: |
          PATH="~/.roswell/bin:$PATH"
          COVERAGE=1 rove aoc-lisp-ng.asd
